media_folder: public/media
public_folder: /media

collections:
  - label: "Seasons"
    name: "seasons"
    folder: "/src/content/seasons"
    create: true
    fields:
    - {lable: "Title", name: "title", widget: "string"}
    - {lable: "Slug", name: "slug", widget: "string"}

backend:
  name: github
  repo: aitorcas23/sveltia-test
  site_domain: www.aitorcas.pp.ua
  base_url: https://www.aitorcas.pp.ua
  auth_endpoint: oauth
