media_folder: public/media
public_folder: /media

collections:
  - label: "Seasons"
    name: "seasons"
    folder: "/src/content/seasons"
    create: true
    fields:
    - {lable: "Title", name: "title", widget: "string"}
    - {lable: "Slug", name: "slug", widget: "string"}

backend:
  name: github
  repo: aitorcas23/sveltia-test
  auth_endpoint: oauth
  site_domain: localhost:3000
  base_url: http://localhost:3000
